oc_platform_home:
    path:    /
    defaults:
       _controller: OCPlatformBundle:Advert:index
oc_platform_view:
    path:    /advert/{id}
    defaults:
       _controller: OCPlatformBundle:Doctrine:view
    requirements:
        id: \d+
oc_platform_add:
    path:    /add/
    defaults: 
        _controller: OCPlatformBundle:Doctrine:add
oc_platform_update:
    path:    /edit/{advertId}
    defaults: 
        _controller: OCPlatformBundle:Doctrine:editImage
    requirements:
        advertId: \d+
oc_platform_addCandidatures:
    path:    /addCandidatures/
    defaults: 
        _controller: OCPlatformBundle:Doctrine:addCandidatures
oc_platform_addCategory:
    path:    /addCategory/{id}
    defaults: 
        _controller: OCPlatformBundle:Doctrine:edit
    requirements:
        id: \d+
oc_platform_deleteCategories:
    path:   /deleteCategories/{id}
    defaults:
        _controller: OCPlatformBundle:Doctrine:deleteCategory
    requirements:
        id: \d+
oc_platform_addCompetences:
    path: /addCompetences/
    defaults:
        _controller: OCPlatformBundle:Doctrine:addCompetences
Oc_platform_viewCompetences:
    path: /competences/{id}
    defaults:
        _controller: OCPlatformBundle:Doctrine:viewSkills
OC_platform_viewAdvertsQueryBuilder:
    path: /adverts/
    defaults:
        _controller: OCPlatformBundle:Doctrine:test
OC_platform_viewAdvertsQueryBuilder1:
    path: /viewadvert/{id}
    defaults:
        _controller: OCPlatformBundle:Doctrine:test2
    requirements:
        id: \d+
            
        
       