oc_platform_home:
    path:    /
    defaults:
       _controller: OCPlatformBundle:Advert:index
oc_platform_view:
    path:    /advert/
    defaults:
       _controller: OCPlatformBundle:Doctrine:view
oc_platform_add:
    path:    /add/
    defaults: 
        _controller: OCPlatformBundle:Advert:add