oc_homepage_home:
    path:     /home
    defaults:
         _controller: OCHomepageBundle:Default:index
# oc_url_form:
    # path: /contact/
    # defaults:
        #_controller: OCHomepageBundle:Default:formcontact
oc_url_redirect:
    path: /redirect
    defaults:
        _controller: OCHomepageBundle:Default:redirect
    requirements:
        mess: "[a-zA-Z0-9-]+"

    
    
